# Generated by Django 5.2.6 on 2025-09-28 15:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code_id', models.CharField(blank=True, max_length=100, null=True)),
                ('invitation_status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('declined', 'Recusado')], default='pending', max_length=20)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('interactions_count', models.IntegerField(default=0)),
                ('personalized_message', models.TextField(blank=True, null=True)),
                ('pre_confirmation_video_url', models.URLField(blank=True, null=True)),
                ('thank_you_video_url', models.URLField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='guests.guest')),
            ],
        ),
    ]
