# Generated by Django 5.2.6 on 2025-09-28 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('completed_missions', models.JSONField(blank=True, default=list)),
                ('secret_missions', models.JSONField(blank=True, default=list)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('invite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to='invitations.invite')),
            ],
        ),
    ]
