# Generated by Django 5.2.6 on 2025-09-28 15:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('avatar_id', models.CharField(blank=True, max_length=100, null=True)),
                ('emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('memories', models.JSONField(blank=True, default=list, null=True)),
                ('favorite_dish', models.CharField(blank=True, max_length=100, null=True)),
                ('favorite_drink', models.CharField(blank=True, max_length=100, null=True)),
                ('dietary_restrictions', models.CharField(blank=True, max_length=200, null=True)),
                ('music_suggestion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
